---
title: Modelo de Classificação para Vítimas Motociclistas de Mortes no Trânsito

format: 
  html: 
    toc: true
    toc-depth: 2
    theme: style.scss
    
lang: pt-br
    
title-block-banner: true
bibliography: references.bib
---

## Resumo

Motocicletas são os veículos mais notórios no campo da segurança viária no que se referem à modais de locomoção urbana com altos índices de acidentes e fatalidades. Mais da metade dos mortos em trânsito incluem motociclistas, ciclistas ou pedestres [@organizaçãomundialdasaúde2018], visto que as motocicletas lideram com o maior número de óbitos desde sua consolidação como um dos principais meios de transporte modernos. Vê-se que a proporção de acidentes de motociclistas está em constante aumento desde 1996 [@vasconcellos2013], e a associação deste modal com serviços de entrega fazem com que os indivíduos desta categoria de motorista sejam frequentemente inseridos em situações de potencial risco [@cunto2017]. Estas mortes configuram um obstáculo de saúde pública nacional, propiciando a geração de diversos estudos focados em ratificar os déficits do sistema de segurança viária do país por meio da reforma de políticas, como a redução da tolerância de concentração de álcool no sangue, a redução do limite de velocidade, a obrigatoriedade de capacetes, entre outros [@miller2018]. Estes aspectos estimulam o presente projeto a investigar a ocorrência de sinistros fatais no trânsito nacional por meio do ajuste de um algoritmo classificador, visando criar um modelo capaz de detectar padrões entre as vítimas motociclistas e apontar a importância estatística de cada variável considerada para sua confecção. Este modelo é uma Regressão Logística que prevê a classificação binária das vítimas (se são ou não motociclistas), se baseando nas variáveis preditivas escolhidas (idade, etnia, sexo, escolaridade, estado civil e o local de ocorrência do óbito). O treinamento do modelo foi efetuado com uma combinação das técnicas de *hold out* e Validação Cruzada, com as métricas para acurácia, precisão e sensibilidade de 0,67, 0,69 e 0,92 respectivamente, utilizando do ajuste logístico para extrair as razões de possibilidade (*odds ratio*) de cada variável.

## Abstract

Motorcycles are one of the most notorious types of transport when it comes to high road crashes and casualty indexes in the field of study of road safety. More than half of global deaths in road crashes included motorcyclists, cyclists and pedestrians in 2018. Motorcycles lead the rankings in terms of road traffic deaths since their consolidation as one of the main means of transport of modern society. In Brazil, the proportion of accidents involving motorcyclists has steadily grown from 1996 to 2010 and they represent the majority of fatal victims in the last decade. This scenario configures an obstacle for public health and trauma prevention, inducing the conception of numerous studies focusing on rectifying the deficiencies within the Brazilian national road safety system through legislative reforms, such as lowering the BAC tolerance, speed limit reduction, mandatory use of helmets, improvement of post-crash care, among others. These aspects motivate this research to investigate road traffic deaths of motorcycle occupants in Brazil, through the adjustment of a classification regression model aiming to inspect personal characteristics of the victims and indicate the individual importance and significance of each variable considered for the developed classifier. The machine learning model presented utilizes the Binary Logistic Regression method to predict a binary class for each analyzed victim (classifying them as either motorcycle occupant or not), based on the predictive features extracted from the Brazilian Ministry of Health database, including age, ethnicity, sex, level of education, marital status and place of death. The fitting of the model is achieved through a combination of "hold out" and Cross Validation sampling techniques, and the odd ratios are are obtained from each variable to evaluate the likelihood of being a based on their category. The study shows that male, ethnically mixed young adults are the individuals most affected by motorcycling related deaths.